# C:\Users\User\Downloads\QA-Form-2026-main\QA-Form-2026-main\netlify.toml

[build]
  base = "client"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://qa-form-2026.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200